import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Check, ChevronLeft, ChevronRight, Circle, CircleDot, Download, Lightbulb, ListTodo, Plus, Settings as SettingsIcon, Sparkles, Wallet, X } from 'lucide-react'
import { useLocation, useNavigate } from 'react-router-dom'
import { db, defaultSettings, effectiveTaskStatus, migrateLegacyAISettings, recurrenceMatches, todayISO, uid, type Budget, type Expense, type Idea, type RecurrenceKind, type Settings, type Task, type TaskStatus } from './db'

type Tab = 'today' | 'calendar' | 'ideas' | 'wallet'
const pad = (n: number) => String(n).padStart(2, '0')
const fmtDate = (iso: string) => new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', weekday: 'long' }).format(new Date(`${iso}T12:00:00`))
const monthKey = (iso: string) => iso.slice(0, 7)
const parseSimpleExpense = (text: string): Partial<Expense> => {
  const amount = Number((text.match(/(?:¥|￥|人民币|rmb)?\s*(\d+(?:\.\d{1,2})?)/i)?.[1] ?? '').trim())
  const category = /午饭|晚饭|早餐|咖啡|吃|餐/.test(text) ? '餐饮' : /地铁|公交|打车|滴滴/.test(text) ? '交通' : /书|课程|学习/.test(text) ? '学习' : '其他'
  return { amountCny: amount || undefined, category, note: text, source: 'manual' }
}
const isISODate = (value: unknown) => typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(new Date(`${value}T12:00:00`).getTime())
export function validateBackup(value: unknown): value is { schemaVersion: 1; tasks: Task[]; ideas: Idea[]; expenses: Expense[]; budgets: Budget[] } {
  if (!value || typeof value !== 'object') return false
  const p = value as Record<string, unknown>
  if (p.schemaVersion !== 1 || !Array.isArray(p.tasks) || !Array.isArray(p.ideas) || !Array.isArray(p.expenses) || !Array.isArray(p.budgets)) return false
  const validTask = (t: any) => t && typeof t.id === 'string' && typeof t.title === 'string' && isISODate(t.date) && ['todo', 'doing', 'done'].includes(t.status)
  const validIdea = (i: any) => i && typeof i.id === 'string' && typeof i.content === 'string' && isISODate(i.date) && Array.isArray(i.tags)
  const validExpense = (e: any) => e && typeof e.id === 'string' && isISODate(e.date) && typeof e.amountCny === 'number' && Number.isFinite(e.amountCny) && e.amountCny > 0 && typeof e.category === 'string'
  const validBudget = (b: any) => b && typeof b.id === 'string' && /^\d{4}-\d{2}$/.test(b.month) && typeof b.category === 'string' && typeof b.limitCny === 'number' && b.limitCny > 0
  return p.tasks.every(validTask) && p.ideas.every(validIdea) && p.expenses.every(validExpense) && p.budgets.every(validBudget)
}

export default function App() {
  const location = useLocation(); const navigate = useNavigate()
  const [tab, setTab] = useState<Tab>('today'); const [selectedDate, setSelectedDate] = useState(todayISO())
  const [tasks, setTasks] = useState<Task[]>([]); const [ideas, setIdeas] = useState<Idea[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]); const [budgets, setBudgets] = useState<Budget[]>([]); const [settings, setSettings] = useState<Settings>(defaultSettings)
  const [showTask, setShowTask] = useState(false); const [showIdea, setShowIdea] = useState(false); const [showExpense, setShowExpense] = useState(false); const [showSettings, setShowSettings] = useState(false); const [showBudget, setShowBudget] = useState(false); const [editingTask, setEditingTask] = useState<Task | null>(null); const [editingIdea, setEditingIdea] = useState<Idea | null>(null)
  const reload = async () => { setTasks(await db.tasks.toArray()); setIdeas(await db.ideas.orderBy('date').reverse().toArray()); setExpenses(await db.expenses.orderBy('date').reverse().toArray()); setBudgets(await db.budgets.toArray()); setSettings((await db.settings.get('main')) ?? defaultSettings) }
  useEffect(() => { void (async () => { const current = await db.settings.get('main'); const next = current ? migrateLegacyAISettings(current) : defaultSettings; await db.settings.put(next); await reload() })() }, [])
  useEffect(() => { const parts = location.pathname.split('/').filter(Boolean); if (parts[0] === 'day' && /^\d{4}-\d{2}-\d{2}$/.test(parts[1] ?? '')) { setSelectedDate(parts[1]); setTab('today') } else if (['calendar', 'ideas', 'wallet'].includes(parts[0])) setTab(parts[0] as Tab); else if (location.pathname === '/') navigate(`/day/${todayISO()}`, { replace: true }) }, [location.pathname, navigate])
  const dayTasks = useMemo(() => tasks.filter((t) => t.date === selectedDate || recurrenceMatches(t.recurrence, t.date, selectedDate)).map((t) => ({ ...t, status: effectiveTaskStatus(t, selectedDate) })), [tasks, selectedDate])
  const dayIdeas = useMemo(() => ideas.filter((i) => i.date === selectedDate), [ideas, selectedDate])
  const nav = (next: Tab) => { if (next === 'today') navigate(`/day/${todayISO()}`); else navigate(`/${next}`) }
  const toggleTask = async (task: Task) => { const source = await db.tasks.get(task.id); if (!source) return; const current = effectiveTaskStatus(source, selectedDate); const status: TaskStatus = current === 'todo' ? 'doing' : current === 'doing' ? 'done' : 'todo'; const now = new Date().toISOString(); if (source.recurrence) { const occurrenceStatuses = { ...(source.occurrenceStatuses ?? {}), [selectedDate]: status }; const occurrenceCompletedAt = { ...(source.occurrenceCompletedAt ?? {}) }; if (status === 'done') occurrenceCompletedAt[selectedDate] = now; else delete occurrenceCompletedAt[selectedDate]; await db.tasks.update(task.id, { occurrenceStatuses, occurrenceCompletedAt, updatedAt: now }) } else await db.tasks.update(task.id, { status, completedAt: status === 'done' ? now : undefined, updatedAt: now }); reload() }
  const deleteTask = async (id: string) => { if (!window.confirm('确定删除这个任务吗？')) return; await db.tasks.delete(id); reload() }
  const totals = expenses.filter((e) => monthKey(e.date) === monthKey(selectedDate)).reduce((sum, e) => sum + e.amountCny, 0)
  const selectedMonthBudgets = budgets.filter((b) => b.month === monthKey(selectedDate)); const totalBudget = selectedMonthBudgets.find((b) => b.category === '*')?.limitCny; const monthBudget = totalBudget ?? selectedMonthBudgets.filter((b) => b.category !== '*').reduce((sum, b) => sum + b.limitCny, 0)

  return <div className="app-shell">
    <header className="topbar"><div className="brand-mark">静日</div><div className="brand-sub">QUIET DAYBOOK</div><div className="top-actions"><button className="icon-btn" onClick={() => setShowSettings(true)} title="设置"><SettingsIcon size={18} /></button></div></header>
    <main className="content">
      {tab === 'today' && <TodayView date={selectedDate} tasks={dayTasks} ideas={dayIdeas} onTask={toggleTask} onDelete={deleteTask} onEdit={(task: Task) => { setEditingTask(task); setShowTask(true) }} onAddTask={() => { setEditingTask(null); setShowTask(true) }} onAddIdea={() => { setEditingIdea(null); setShowIdea(true) }} onEditIdea={(idea: Idea) => { setEditingIdea(idea); setShowIdea(true) }} onAddExpense={() => setShowExpense(true)} />}
      {tab === 'calendar' && <CalendarView date={selectedDate} tasks={tasks} onDate={(d: string) => navigate(`/day/${d}`)} onPrev={() => setSelectedDate(shiftMonth(selectedDate, -1))} onNext={() => setSelectedDate(shiftMonth(selectedDate, 1))} />}
      {tab === 'ideas' && <IdeasView ideas={ideas} onAdd={() => { setEditingIdea(null); setShowIdea(true) }} onEdit={(idea: Idea) => { setEditingIdea(idea); setShowIdea(true) }} />}
      {tab === 'wallet' && <WalletView expenses={expenses} budgets={budgets} month={monthKey(selectedDate)} total={totals} budget={monthBudget} onAdd={() => setShowExpense(true)} onBudget={() => setShowBudget(true)} />}
    </main>
    <nav className="bottom-nav">{([['today', ListTodo, '今天'], ['calendar', CalendarDays, '月历'], ['ideas', Lightbulb, '想法'], ['wallet', Wallet, '钱包']] as const).map(([id, Icon, label]) => <button key={id} className={tab === id ? 'nav-item active' : 'nav-item'} onClick={() => nav(id)}><Icon size={19} /><span>{label}</span></button>)}</nav>
    {showTask && <TaskModal initial={editingTask} date={selectedDate} onClose={() => setShowTask(false)} onSaved={() => { setShowTask(false); reload() }} />}
    {showIdea && <IdeaModal initial={editingIdea} date={selectedDate} onClose={() => setShowIdea(false)} onSaved={() => { setShowIdea(false); reload() }} />}
    {showExpense && <ExpenseModal settings={settings} date={selectedDate} onClose={() => setShowExpense(false)} onSaved={() => { setShowExpense(false); reload() }} />}
    {showSettings && <SettingsModal settings={settings} onClose={() => setShowSettings(false)} onSaved={(s: Settings) => { setSettings(s); setShowSettings(false) }} />}
    {showBudget && <BudgetModal month={monthKey(selectedDate)} budgets={budgets} categories={settings.categories} onClose={() => setShowBudget(false)} onSaved={() => { setShowBudget(false); reload() }} />}
  </div>
}

function TodayView({ date, tasks, ideas, onTask, onDelete, onEdit, onAddTask, onAddIdea, onEditIdea, onAddExpense }: any) { return <section className="page"><div className="date-hero"><div className="date-tab">{new Date(`${date}T12:00:00`).getDate()}</div><div><p className="eyebrow">{new Date(`${date}T12:00:00`).getFullYear()} / {pad(new Date(`${date}T12:00:00`).getMonth() + 1)}</p><h1>{fmtDate(date)}</h1><p className="muted">把今天过成一页清楚的纸。</p></div></div><div className="quick-actions"><button className="primary" onClick={onAddTask}><Plus size={17} /> 新任务</button><button onClick={onAddIdea}><Lightbulb size={16} /> 写想法</button><button onClick={onAddExpense}><Wallet size={16} /> 记一笔</button></div><div className="section-grid"><div className="panel"><div className="panel-head"><div><p className="eyebrow">TODAY'S LIST</p><h2>任务</h2></div><span className="count">{tasks.length}</span></div>{tasks.length === 0 ? <Empty text="今天还没有任务" action="添加第一件事" onClick={onAddTask} /> : <div className="task-list">{tasks.map((t: Task) => <div className="task-row" key={t.id}><button className={`status-dot ${t.status}`} onClick={() => onTask(t)} title="切换状态">{t.status === 'done' ? <Check size={13} /> : t.status === 'doing' ? <CircleDot size={13} /> : <Circle size={13} />}</button><button className={t.status === 'done' ? 'task-copy task-copy-btn done' : 'task-copy task-copy-btn'} onClick={() => onEdit(t)}><span>{t.title}</span>{t.note && <small>{t.note}</small>}</button><button className="ghost-delete" onClick={() => onDelete(t.id)} title="删除任务"><X size={15} /></button></div>)}</div>}</div><div className="panel idea-panel"><div className="panel-head"><div><p className="eyebrow">FIELD NOTES</p><h2>今日想法</h2></div><button className="round-btn" onClick={onAddIdea}><Plus size={17} /></button></div>{ideas.length === 0 ? <Empty text="留下一点今天的念头" action="写一条想法" onClick={onAddIdea} /> : ideas.map((i: Idea) => <button className="idea-snippet idea-button" key={i.id} onClick={() => onEditIdea(i)}><p>{i.content}</p><div>{i.tags.map((tag) => <span className="tag" key={tag}>#{tag}</span>)}</div></button>)}</div></div></section> }

function CalendarView({ date, tasks, onDate, onPrev, onNext }: any) { const d = new Date(`${date}T12:00:00`); const year = d.getFullYear(); const month = d.getMonth(); const first = new Date(year, month, 1); const offset = (first.getDay() + 6) % 7; const days = new Date(year, month + 1, 0).getDate(); const cells = Array.from({ length: Math.ceil((offset + days) / 7) * 7 }, (_, i) => { const n = i - offset + 1; return n > 0 && n <= days ? `${year}-${pad(month + 1)}-${pad(n)}` : null }); return <section className="page"><div className="page-title"><div><p className="eyebrow">CALENDAR</p><h1>{year} 年 {month + 1} 月</h1></div><div className="month-nav"><button onClick={onPrev}><ChevronLeft size={18} /></button><button onClick={() => onDate(todayISO())}>今天</button><button onClick={onNext}><ChevronRight size={18} /></button></div></div><div className="calendar-card"><div className="week-head">{['一','二','三','四','五','六','日'].map((w) => <span key={w}>{w}</span>)}</div><div className="calendar-grid">{cells.map((iso, i) => { const count = iso ? tasks.filter((t: Task) => t.date === iso || recurrenceMatches(t.recurrence, t.date, iso)).length : 0; return <button className={iso === date ? 'day-cell selected' : iso === todayISO() ? 'day-cell today' : 'day-cell'} key={i} disabled={!iso} onClick={() => iso && onDate(iso)}>{iso && <><b>{Number(iso.slice(-2))}</b>{count > 0 && <span className="day-mark">{count}</span>}</>}</button> })}</div></div><p className="calendar-hint">点击日期查看当天任务与想法</p></section> }

function IdeasView({ ideas, onAdd, onEdit }: { ideas: Idea[]; onAdd: () => void; onEdit: (idea: Idea) => void }) { const [filter, setFilter] = useState('全部'); const tags = ['全部', ...Array.from(new Set(ideas.flatMap((i) => i.tags)))]; const list = filter === '全部' ? ideas : ideas.filter((i) => i.tags.includes(filter)); return <section className="page"><div className="page-title"><div><p className="eyebrow">FIELD NOTES</p><h1>想法集</h1><p className="muted">让零散的念头有地方长大。</p></div><button className="primary" onClick={onAdd}><Plus size={17} /> 新想法</button></div><div className="filter-row">{tags.map((t) => <button className={filter === t ? 'filter active' : 'filter'} key={t} onClick={() => setFilter(t)}>{t}</button>)}</div>{list.length === 0 ? <Empty text="还没有想法记录" action="写下第一条" onClick={onAdd} /> : <div className="idea-feed">{list.map((i) => <button className="idea-card idea-button" key={i.id} onClick={() => onEdit(i)}><div className="idea-date"><b>{new Date(`${i.date}T12:00:00`).getDate()}</b><span>{new Date(`${i.date}T12:00:00`).toLocaleDateString('zh-CN', { month: 'short', weekday: 'short' })}</span></div><div><p>{i.content}</p><div>{i.tags.map((tag) => <span className="tag" key={tag}>#{tag}</span>)}</div></div></button>)}</div>}</section> }

function WalletView({ expenses, budgets, month, total, budget, onAdd, onBudget }: any) { const grouped = expenses.filter((e: Expense) => monthKey(e.date) === month); const byCat = grouped.reduce((a: any, e: Expense) => { a[e.category] = (a[e.category] || 0) + e.amountCny; return a }, {}); const categoryBudget = (cat: string) => budgets.find((b: Budget) => b.month === month && b.category === cat)?.limitCny; return <section className="page"><div className="page-title"><div><p className="eyebrow">MONEY, QUIETLY</p><h1>钱包</h1><p className="muted">{month} 的每一笔，都值得被看见。</p></div><button className="primary" onClick={onAdd}><Plus size={17} /> 记一笔</button></div><div className="money-summary"><div><span>本月已花</span><strong>¥{total.toFixed(2)}</strong></div><div><span>预算</span><strong>{budget ? `¥${budget.toFixed(2)}` : '未设置'}</strong></div><div className={budget && total > budget ? 'over' : ''}><span>剩余</span><strong>{budget ? `¥${(budget - total).toFixed(2)}` : '—'}</strong></div></div><div className="quick-actions"><button onClick={onBudget}><SettingsIcon size={16} /> 设置本月预算</button></div><div className="section-grid wallet-grid"><div className="panel"><div className="panel-head"><div><p className="eyebrow">BREAKDOWN</p><h2>分类统计</h2></div></div>{Object.keys(byCat).length === 0 ? <Empty text="还没有开销记录" action="记下第一笔" onClick={onAdd} /> : Object.entries(byCat).map(([cat, amount]) => { const limit = categoryBudget(cat); return <div className="breakdown-row" key={cat}><span>{cat}{limit && <small> / ¥{limit}</small>}</span><div className="bar"><i className={limit && (amount as number) > limit ? 'over-bar' : ''} style={{ width: `${Math.min(100, limit ? ((amount as number) / limit) * 100 : ((amount as number) / Math.max(total, 1)) * 100)}%` }} /></div><b>¥{(amount as number).toFixed(2)}</b></div> })}</div><div className="panel"><div className="panel-head"><div><p className="eyebrow">RECENT</p><h2>最近开销</h2></div></div>{grouped.slice(0, 8).map((e: Expense) => <div className="expense-row" key={e.id}><div><b>{e.category}</b><small>{e.note || e.merchant || '未添加备注'}</small></div><strong>¥{e.amountCny.toFixed(2)}</strong></div>)}</div></div></section> }

function Empty({ text, action, onClick }: any) { return <div className="empty"><p>{text}</p><button onClick={onClick}>{action} <Plus size={14} /></button></div> }
function Modal({ title, children, onClose }: any) { return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose}><X size={18} /></button></div>{children}</div></div> }
function TaskModal({ initial, date, onClose, onSaved }: { initial: Task | null; date: string; onClose: () => void; onSaved: () => void }) { const [title, setTitle] = useState(initial?.title ?? ''); const [note, setNote] = useState(initial?.note ?? ''); const [kind, setKind] = useState<RecurrenceKind | ''>(initial?.recurrence?.kind ?? ''); const save = async () => { if (!title.trim()) return; const now = new Date().toISOString(); if (initial) await db.tasks.update(initial.id, { title: title.trim(), note: note.trim(), recurrence: kind ? { kind } : undefined, updatedAt: now }); else await db.tasks.add({ id: uid(), title: title.trim(), note: note.trim(), date, status: 'todo', recurrence: kind ? { kind } : undefined, createdAt: now, updatedAt: now }); onSaved() }; return <Modal title={initial ? '编辑任务' : '新任务'} onClose={onClose}><label>任务名称<input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} placeholder="例如：写完产品说明" /></label><label>备注<textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="可选" /></label><label>重复<select value={kind} onChange={(e) => setKind(e.target.value as any)}><option value="">不重复</option><option value="daily">每天</option><option value="weekdays">工作日</option><option value="weekly">每周</option><option value="monthly">每月</option></select></label><button className="primary full" onClick={save}>保存任务</button></Modal> }
function IdeaModal({ initial, date, onClose, onSaved }: { initial: Idea | null; date: string; onClose: () => void; onSaved: () => void }) { const [content, setContent] = useState(initial?.content ?? ''); const [tags, setTags] = useState(initial?.tags.join(', ') ?? '随手记录'); const save = async () => { if (!content.trim()) return; const now = new Date().toISOString(); const next = { content: content.trim(), tags: tags.split(/[,，\s]+/).filter(Boolean), updatedAt: now }; if (initial) await db.ideas.update(initial.id, next); else await db.ideas.add({ id: uid(), date, ...next, createdAt: now }); onSaved() }; const remove = async () => { if (!initial || !window.confirm('确定删除这条想法吗？')) return; await db.ideas.delete(initial.id); onSaved() }; return <Modal title={initial ? '编辑想法' : '写下一个想法'} onClose={onClose}><label>内容<textarea autoFocus value={content} onChange={(e) => setContent(e.target.value)} placeholder="今天想到什么？" rows={6} /></label><label>标签<input value={tags} onChange={(e) => setTags(e.target.value)} placeholder="创新, 决定" /></label><button className="primary full" onClick={save}>保存想法</button>{initial && <button className="danger full" onClick={remove}>删除这条想法</button>}</Modal> }
function ExpenseModal({ settings, date, onClose, onSaved }: { settings: Settings; date: string; onClose: () => void; onSaved: () => void }) {
  const [text, setText] = useState(''); const [parsed, setParsed] = useState<any>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  const persist = async (value: any, source: 'manual' | 'ai') => { if (!value?.amountCny || Number(value.amountCny) <= 0 || !/^\d{4}-\d{2}-\d{2}$/.test(value.date ?? '')) return false; await db.expenses.add({ id: uid(), date: value.date, amountCny: Number(value.amountCny), category: value.category || '其他', note: value.note || text, merchant: value.merchant, paymentMethod: value.paymentMethod, source, aiConfidence: value.confidence, createdAt: new Date().toISOString() }); return true }
  const parse = async () => { setBusy(true); setMessage(''); let result: any = null; let aiSucceeded = false
    if (settings.aiApiKey) { try { const res = await fetch(`${settings.aiBaseUrl.replace(/\/$/, '')}/chat/completions`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${settings.aiApiKey}` }, body: JSON.stringify({ model: settings.aiModel, temperature: 0, response_format: { type: 'json_object' }, messages: [{ role: 'system', content: `Extract an expense as JSON with date YYYY-MM-DD, amountCny number, category, note, merchant, paymentMethod and confidence 0-1. Allowed categories: ${settings.categories.join(', ')}. Use the provided date if none is stated. Return JSON only.` }, { role: 'user', content: `Date: ${date}\nText: ${text}` }] }) }); if (!res.ok) throw new Error(`HTTP ${res.status}`); const data = await res.json(); result = JSON.parse(data.choices?.[0]?.message?.content || '{}'); aiSucceeded = true } catch { setMessage('AI 接口不可用，已改用本地关键词解析。请检查地址、Key 和 CORS 设置。') } }
    if (!result) result = parseSimpleExpense(text)
    const next = { ...result, date: result.date || date, confidence: result.confidence ?? 0.65 }
    if (aiSucceeded && result.date && result.amountCny && next.confidence >= settings.confidenceThreshold) { const saved = await persist(next, 'ai'); setBusy(false); if (saved) { onSaved(); return } }
    setParsed(next); setBusy(false)
  }
  const save = async () => { if (await persist(parsed, settings.aiApiKey && parsed?.confidence ? 'ai' : 'manual')) onSaved() }
  return <Modal title="记一笔开销" onClose={onClose}><div className="ai-input"><Sparkles size={17} /><input autoFocus value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && parse()} placeholder="例如：午饭 32 元，和同事吃" /><button onClick={parse} disabled={!text.trim() || busy}>{busy ? '解析中' : '解析'}</button></div>{message && <p className="inline-warning">{message}</p>}{parsed && <div className="parse-card editable"><label><span>金额</span><input type="number" min="0.01" step="0.01" value={parsed.amountCny ?? ''} onChange={(e) => setParsed({ ...parsed, amountCny: e.target.value })} /></label><label><span>分类</span><select value={parsed.category || '其他'} onChange={(e) => setParsed({ ...parsed, category: e.target.value })}>{settings.categories.map((c) => <option key={c}>{c}</option>)}</select></label><label><span>日期</span><input type="date" value={parsed.date || date} onChange={(e) => setParsed({ ...parsed, date: e.target.value })} /></label><label className="wide"><span>备注</span><input value={parsed.note || text} onChange={(e) => setParsed({ ...parsed, note: e.target.value })} /></label><small>请确认解析结果后保存（置信度 {Math.round((parsed.confidence || 0) * 100)}%）</small></div>}<button className="primary full" onClick={save} disabled={!parsed?.amountCny}>保存开销</button><p className="form-hint">高置信度 AI 结果会自动入账；未配置 AI 时使用本地解析。不要在公共设备保存 API Key。</p></Modal>
}
function BudgetModal({ month, budgets, categories, onClose, onSaved }: { month: string; budgets: Budget[]; categories: string[]; onClose: () => void; onSaved: () => void }) { const existing = Object.fromEntries(budgets.filter((b) => b.month === month).map((b) => [b.category, String(b.limitCny)])); const [values, setValues] = useState<Record<string, string>>(existing); const save = async () => { for (const category of ['*', ...categories]) { const id = `${month}-${category}`; const n = Number(values[category]); if (n > 0) await db.budgets.put({ id, month, category, limitCny: n }); else await db.budgets.delete(id) } onSaved() }; return <Modal title={`${month} 预算`} onClose={onClose}><p className="form-hint">可只设置总预算，也可为常用分类分别设置额度。</p><div className="budget-fields"><label>总预算<input type="number" min="0" step="0.01" value={values['*'] ?? ''} onChange={(e) => setValues({ ...values, '*': e.target.value })} placeholder="例如：5000" /></label>{categories.map((category) => <label key={category}>{category}<input type="number" min="0" step="0.01" value={values[category] ?? ''} onChange={(e) => setValues({ ...values, [category]: e.target.value })} placeholder="不设置" /></label>)}</div><button className="primary full" onClick={save}>保存预算</button></Modal> }
function SettingsModal({ settings, onClose, onSaved }: { settings: Settings; onClose: () => void; onSaved: (settings: Settings) => void }) {
  const [form, setForm] = useState(settings)
  const exportData = async () => { const { aiApiKey: _secret, ...safeSettings } = form; const payload = { schemaVersion: 1, exportedAt: new Date().toISOString(), tasks: await db.tasks.toArray(), ideas: await db.ideas.toArray(), expenses: await db.expenses.toArray(), budgets: await db.budgets.toArray(), settings: safeSettings }; const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `quiet-daybook-${todayISO()}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }
  const importData = async (e: React.ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; try { const p = JSON.parse(await file.text()); if (!validateBackup(p)) throw new Error('invalid'); await db.transaction('rw', db.tasks, db.ideas, db.expenses, db.budgets, async () => { await db.tasks.clear(); await db.ideas.clear(); await db.expenses.clear(); await db.budgets.clear(); await db.tasks.bulkAdd(p.tasks); await db.ideas.bulkAdd(p.ideas); await db.expenses.bulkAdd(p.expenses); await db.budgets.bulkAdd(p.budgets) }); alert('备份已恢复。API Key 出于安全原因不会随备份导入。'); onSaved(form) } catch { alert('备份文件格式不正确：请检查版本、日期、金额和必填字段。') } finally { e.target.value = '' } }
  const clearAll = async () => { if (!window.confirm('确定清空全部任务、想法、开销和预算吗？此操作无法撤销，请先导出备份。')) return; await db.transaction('rw', db.tasks, db.ideas, db.expenses, db.budgets, async () => { await db.tasks.clear(); await db.ideas.clear(); await db.expenses.clear(); await db.budgets.clear() }); onSaved(form); window.location.reload() }
  return <Modal title="设置" onClose={onClose}><p className="settings-note">数据只保存在这台设备的浏览器中，不会自动同步到手机或其他电脑。</p><label>千问 API 地址<input value={form.aiBaseUrl} onChange={(e) => setForm({ ...form, aiBaseUrl: e.target.value })} /></label><label>千问模型<input list="qwen-models" value={form.aiModel} onChange={(e) => setForm({ ...form, aiModel: e.target.value })} /><datalist id="qwen-models"><option value="qwen-plus" /><option value="qwen-turbo" /><option value="qwen-max" /></datalist></label><label>百炼 API Key<input type="password" value={form.aiApiKey} onChange={(e) => setForm({ ...form, aiApiKey: e.target.value })} placeholder="sk-...；可留空使用本地解析" /></label><p className="form-hint">在 <a href="https://bailian.console.aliyun.com/?tab=model#/api-key" target="_blank" rel="noreferrer">阿里云百炼控制台</a>创建 Key。Key 只保存在本机 IndexedDB，不会进入备份；不要在公共电脑保存。</p><div className="settings-actions"><button onClick={exportData}><Download size={16} /> 导出 JSON</button><label className="file-btn">导入 JSON<input type="file" accept="application/json" onChange={importData} /></label></div><button className="primary full" onClick={async () => { const saved = { ...form, id: 'main' as const }; await db.settings.put(saved); onSaved(saved) }}>保存设置</button><button className="danger full" onClick={clearAll}>清空全部数据</button></Modal>
}
function shiftMonth(iso: string, delta: number) { const d = new Date(`${iso}T12:00:00`); d.setDate(1); d.setMonth(d.getMonth() + delta); return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-01` }
